import { HourEntry, Category } from "./types";
import { getWeekLabel } from "./utils";

const DAYS = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];

export async function exportToPDF(weekId: string, entries: HourEntry[], categories: Category[]): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  const getCatName = (id: string) => categories.find(c => c.id === id)?.name ?? id;
  const getCatColor = (id: string) => {
    const hex = categories.find(c => c.id === id)?.color ?? "#334155";
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b] as [number, number, number];
  };

  // Title
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 60);
  doc.text("168 Hours — Weekly Tracker", 14, 16);

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 140);
  doc.text(getWeekLabel(weekId), 14, 24);

  // Build table data: 24 rows × 7 days
  const tableData: string[][] = [];
  for (let hour = 0; hour < 24; hour++) {
    const row: string[] = [`${String(hour).padStart(2,"0")}:00`];
    for (let day = 0; day < 7; day++) {
      const e = entries.find(e => e.day === day && e.hour === hour);
      row.push(e?.category ? `${getCatName(e.category)}${e.title ? `\n${e.title}` : ""}` : "");
    }
    tableData.push(row);
  }

  autoTable(doc, {
    startY: 30,
    head: [["Hour", ...DAYS]],
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      overflow: "linebreak",
      minCellHeight: 8,
    },
    headStyles: {
      fillColor: [30, 20, 60],
      textColor: [200, 180, 255],
      fontStyle: "bold",
      halign: "center",
    },
    columnStyles: {
      0: { fillColor: [15, 15, 30], textColor: [150, 140, 200], fontStyle: "bold", halign: "center", cellWidth: 16 },
    },
    didDrawCell: (data: { section: string; column: { index: number }; row: { index: number }; cell: { styles: { fillColor: [number,number,number] | string; textColor: [number,number,number] | string } } }) => {
      if (data.section === "body" && data.column.index > 0) {
        const hour = data.row.index;
        const day = data.column.index - 1;
        const e = entries.find(e => e.day === day && e.hour === hour);
        if (e?.category) {
          const [r, g, b] = getCatColor(e.category);
          data.cell.styles.fillColor = [Math.min(255, r + 160), Math.min(255, g + 160), Math.min(255, b + 160)] as [number,number,number];
          data.cell.styles.textColor = [r, g, b] as [number,number,number];
        }
      }
    },
    alternateRowStyles: { fillColor: [245, 244, 252] },
    margin: { top: 30, left: 7, right: 7 },
  });

  // Summary at bottom
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? 180;
  if (finalY < 190) {
    doc.setFontSize(9);
    doc.setTextColor(100, 90, 160);
    const logged = entries.filter(e => e.category).length;
    doc.text(`${logged} / 168 hours logged  ·  Generated by 168 Hours`, 14, finalY + 8);
  }

  doc.save(`168hours-${weekId}.pdf`);
}
