// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/168hours-designs/ArcticBlue.tsx": () => import("../components/mockups/168hours-designs/ArcticBlue.tsx"),
  "./components/mockups/168hours-designs/ObsidianPurple.tsx": () => import("../components/mockups/168hours-designs/ObsidianPurple.tsx"),
  "./components/mockups/168hours-designs/TerminalGreen.tsx": () => import("../components/mockups/168hours-designs/TerminalGreen.tsx"),
  "./components/mockups/color-palettes/Arctic.tsx": () => import("../components/mockups/color-palettes/Arctic.tsx"),
  "./components/mockups/color-palettes/CloudLight.tsx": () => import("../components/mockups/color-palettes/CloudLight.tsx"),
  "./components/mockups/color-palettes/Ember.tsx": () => import("../components/mockups/color-palettes/Ember.tsx"),
  "./components/mockups/color-palettes/Forest.tsx": () => import("../components/mockups/color-palettes/Forest.tsx"),
  "./components/mockups/color-palettes/MintFresh.tsx": () => import("../components/mockups/color-palettes/MintFresh.tsx"),
  "./components/mockups/color-palettes/Purple.tsx": () => import("../components/mockups/color-palettes/Purple.tsx"),
  "./components/mockups/color-palettes/RoseQuartz.tsx": () => import("../components/mockups/color-palettes/RoseQuartz.tsx"),
  "./components/mockups/color-palettes/Slate.tsx": () => import("../components/mockups/color-palettes/Slate.tsx"),
  "./components/mockups/color-palettes/SoftLavender.tsx": () => import("../components/mockups/color-palettes/SoftLavender.tsx"),
  "./components/mockups/color-palettes/WarmSand.tsx": () => import("../components/mockups/color-palettes/WarmSand.tsx"),
  "./components/mockups/grid-variants/GlassCards.tsx": () => import("../components/mockups/grid-variants/GlassCards.tsx"),
  "./components/mockups/grid-variants/PillBadge.tsx": () => import("../components/mockups/grid-variants/PillBadge.tsx"),
  "./components/mockups/grid-variants/SolidBlocks.tsx": () => import("../components/mockups/grid-variants/SolidBlocks.tsx")
};
